"""add channel_type to tiktok_projects

Revision ID: 151409122f54
Revises: f6a7b8c9d0e1
Create Date: 2026-04-21 00:44:03.612735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '151409122f54'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_pieces', sa.Column('audio_url', sa.String(length=500), nullable=True))
    op.add_column('content_pieces', sa.Column('audio_voice_id', sa.String(length=100), nullable=True))
    op.add_column('content_pieces', sa.Column('audio_duration_s', sa.Float(), nullable=True))
    op.add_column('content_pieces', sa.Column('heygen_hook_url', sa.String(length=1000), nullable=True))
    op.add_column('content_pieces', sa.Column('heygen_cta_url', sa.String(length=1000), nullable=True))
    op.add_column('tiktok_projects', sa.Column(
        'channel_type', sa.String(length=30),
        nullable=False,
        server_default='kenh2_real_review',
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiktok_projects', 'channel_type')
    op.drop_column('content_pieces', 'heygen_cta_url')
    op.drop_column('content_pieces', 'heygen_hook_url')
    op.drop_column('content_pieces', 'audio_duration_s')
    op.drop_column('content_pieces', 'audio_voice_id')
    op.drop_column('content_pieces', 'audio_url')
    # ### end Alembic commands ###
