"""add final_video_url ready_to_post_at to tiktok_projects

Revision ID: 99c497f90c21
Revises: 151409122f54
Create Date: 2026-04-22 01:43:14.624079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c497f90c21'
down_revision: Union[str, None] = '151409122f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tiktok_projects', sa.Column('final_video_url', sa.String(length=500), nullable=True))
    op.add_column('tiktok_projects', sa.Column('ready_to_post_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tiktok_projects', 'ready_to_post_at')
    op.drop_column('tiktok_projects', 'final_video_url')
    # ### end Alembic commands ###
