"""add_ai_training_data

Revision ID: ffc02157caee
Revises: 967ba0427f3c
Create Date: 2026-04-08 16:28:30.412130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.compat import GUID


# revision identifiers, used by Alembic.
revision: str = 'ffc02157caee'
down_revision: Union[str, None] = '967ba0427f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_training_data',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('product_platform', sa.String(length=50), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('quality_signal', sa.String(length=30), nullable=False),
    sa.Column('source_content_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_training_data_content_type'), 'ai_training_data', ['content_type'], unique=False)
    op.create_index(op.f('ix_ai_training_data_product_category'), 'ai_training_data', ['product_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_training_data_product_category'), table_name='ai_training_data')
    op.drop_index(op.f('ix_ai_training_data_content_type'), table_name='ai_training_data')
    op.drop_table('ai_training_data')
    # ### end Alembic commands ###
